name: PR Labeler

on:
  push:
    branches:
      - 'main'
    tags: [*v]
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'     

concurrency:
group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: trueß

jobs:
  run-rust-ci-workflow:
    uses: brunolmarques/gha-reusable-workflows/.github.workflows/pr-labeler.yaml@v1.0