name: PR Labeler

on:
 workflow_call:

jobs: 
  pr-labeler:
    runs-on: ubuntu-latest

    steps:
      - id: label-pr
        uses: actions/labeler@v4

      - id: get-change-size
        run: |
          echo"CHANGE_SIZE=$(git log --numstat --pretty="%H" ${{ github.ref }} main | awk 'NF==3 {plus+=$1; minus+=$2} END {printf("%d\n", 'plus+minus')}')" >> $GITHUB_OUTPUT

      - id: change-label
        run: |
          size=${{ steps.get-change-size.outputs.CHANGE_SIZE}}
          if [ "$size" -le 10 ]; then
            echo "SIZE_LABEL='sm'" >> $GITHUB_OUTPUT
          if [ "$size" -le 30 ]; then
            echo "SIZE_LABEL='md'" >> $GITHUB_OUTPUT
          if [ "$size" -le 80 ]; then
            echo "SIZE_LABEL='lg'" >> $GITHUB_OUTPUT
          else
            echo "SIZE_LABEL='xl'" >> $GITHUB_OUTPUT
          fi

      - name: Add size label to Pull Request
        env:
          GITHUB_TOKEN: ${{ secrects.GITHUB_TOKEN }}
          LABEL: ${{ steps.change-label.outputs.SIZE_LABEL }}
        run: |
          curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
          -d '["'"$LABEL"'"]'