name: Rust CI

on:
 workflow_call:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: nightly

      - name: Install Clippy and Rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Check code format
        run: |
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          cargo clippy --all-targets -- -D warnings
          
      - name: Analyze security breaches for dependencies
        run: |
          cargo audit

      - name: Build and test code
        run: |
          cargo build --verbose
          cargo test --verbose