name: Rust CI

on:
 workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Install Clippy and Rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Check code format
        run: |
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          cargo clippy --all-targets -- -D warnings

      - name: Run tests
        run: |
          cargo test --all

      - name: Generate code coverage report
        run: |
          cargo install tarpaulin
          cargo tarpaulin --all --ciserver github-actions --coveralls ${{ github.event_name == 'pull_request' }}

      - name: Analyze security breaches for dependencies
        run: |
          cargo audit